version: '3.4'

services:
  pdfgenerator:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=5000
      - PDF_SECRET=my_private_test_secret
      - NODE_ENV=production
    ports:
      - 5000:5000
